import { CatalogItem } from '@/types/modelSources';

export const PRE_APPROVED_CATALOG: CatalogItem[] = [
  {
    id: 'cat-modular-desk-tray',
    name: 'Modular Honeycomb Desk Organizer',
    category: 'Office & Desk',
    description: 'Interlocking hexagonal pen, cable, and USB drive tray with smooth beveled edges.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 95, y: 82, z: 45 },
    volumeCm3: 48.2,
    basePriceEur: 14.5,
    printTimeHours: 2.8,
    recommendedMaterial: 'PLA',
    tag: 'Best Seller',
    presetId: 'mechanical-bracket',
  },
  {
    id: 'cat-phone-stand-cable',
    name: 'Ergonomic Phone Stand with Cable Channel',
    category: 'Office & Desk',
    description: 'Sturdy 60-degree viewing angle with integrated USB-C pass-through slot.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 75, y: 85, z: 90 },
    volumeCm3: 54.0,
    basePriceEur: 16.2,
    printTimeHours: 3.1,
    recommendedMaterial: 'PLA',
    tag: 'Commercial Approved',
    presetId: 'architectural-canal-house',
  },
  {
    id: 'cat-caliper-wall-dock',
    name: 'Digital Caliper Magnetic Wall Mount',
    category: 'Tools & Workshop',
    description: 'Precision snug-fit holder for Mitutoyo and standard 150mm digital calipers.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 45, y: 40, z: 28 },
    volumeCm3: 22.4,
    basePriceEur: 9.8,
    printTimeHours: 1.4,
    recommendedMaterial: 'PETG',
    tag: 'Industrial Grade',
    presetId: 'mechanical-bracket',
  },
  {
    id: 'cat-bit-storage-grid',
    name: '1/4" Hex Screwdriver Bit Organizer Tray',
    category: 'Tools & Workshop',
    description: 'Holds 24 standard 1/4" hex driver bits with high-retention friction fit.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 80, y: 60, z: 20 },
    volumeCm3: 29.5,
    basePriceEur: 11.2,
    printTimeHours: 1.8,
    recommendedMaterial: 'PETG',
    tag: 'High Precision',
    presetId: 'drone-rotor-guard',
  },
  {
    id: 'cat-headphone-hanger',
    name: 'Heavy-Duty Clamp Under-Desk Headphone Mount',
    category: 'Tech & Gadgets',
    description: 'Saves desk space with curved headband support preventing cushion indentation.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 65, y: 70, z: 55 },
    volumeCm3: 41.0,
    basePriceEur: 13.9,
    printTimeHours: 2.5,
    recommendedMaterial: 'PETG',
    tag: 'Load Tested 5kg',
    presetId: 'mechanical-bracket',
  },
  {
    id: 'cat-watch-magsafe-dock',
    name: 'Dual Smartwatch & MagSafe Nightstand Dock',
    category: 'Tech & Gadgets',
    description: 'Weighted base design with snap-in channels for original charging pucks.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 105, y: 80, z: 70 },
    volumeCm3: 62.8,
    basePriceEur: 18.5,
    printTimeHours: 3.6,
    recommendedMaterial: 'PLA',
    tag: 'Clean Minimal',
    presetId: 'ergonomic-knob',
  },
  {
    id: 'cat-plant-pot-drainage',
    name: 'Parametric Geometric Succulent Pot with Saucer',
    category: 'Home & Living',
    description: 'Modern Voronoi textured plant pot with built-in water drainage tray.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 80, y: 80, z: 75 },
    volumeCm3: 56.0,
    basePriceEur: 15.8,
    printTimeHours: 3.2,
    recommendedMaterial: 'PLA',
    tag: 'Interior Decor',
    presetId: 'architectural-canal-house',
  },
  {
    id: 'cat-bag-clips-set',
    name: 'Heavy-Duty Snap-Lock Food Bag Clips (3-Pack)',
    category: 'Home & Living',
    description: 'Airtight flexible snap mechanism engineered for over 10,000 hinge cycles.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80',
    dimensions: { x: 110, y: 25, z: 18 },
    volumeCm3: 18.2,
    basePriceEur: 8.5,
    printTimeHours: 1.2,
    recommendedMaterial: 'PETG',
    tag: 'Food Safe PETG',
    presetId: 'drone-rotor-guard',
  },
];
