import { BenchmarkPortfolioItem, CustomerOrder } from '@/types';

export const BENCHMARK_PORTFOLIO: BenchmarkPortfolioItem[] = [
  {
    id: 'port-1',
    title: 'TU Delft Solar Boat Structural Hydrofoil Bracket',
    category: 'Engineering & Marine',
    image: 'bracket',
    material: 'PETG',
    dimensions: { x: 120, y: 75, z: 45 },
    printDurationHours: 4.5,
    priceEur: 24.80,
    clientType: 'Student',
    city: 'Delft',
    description: 'Custom carbon-fiber reinforced mounting bracket built to withstand hydrodynamic drag and vibration in open water testing.',
  },
  {
    id: 'port-2',
    title: 'Keizersgracht Heritage Facade Scale 1:50',
    category: 'Architecture & Urban',
    image: 'facade',
    material: 'RESIN',
    dimensions: { x: 110, y: 195, z: 28 },
    printDurationHours: 6.2,
    priceEur: 52.40,
    clientType: 'Architecture Firm',
    city: 'Amsterdam',
    description: 'High-detail stereolithography replica featuring historic Dutch step-gable brickwork and ornate window frames for a municipality planning committee.',
  },
  {
    id: 'port-3',
    title: 'Hospital ICU Ventilator Connector Replacement',
    category: 'Medical & Functional',
    image: 'valve',
    material: 'ABS',
    dimensions: { x: 42, y: 38, z: 62 },
    printDurationHours: 2.1,
    priceEur: 16.50,
    clientType: 'Engineering Lab',
    city: 'Utrecht',
    description: 'Emergency replacement autoclave-safe manifold adapter printed with zero porosity infill and heat-smoothed walls.',
  },
  {
    id: 'port-4',
    title: 'Custom Ergonomic Trackball Housing',
    category: 'Product Design',
    image: 'mouse',
    material: 'PLA',
    dimensions: { x: 145, y: 92, z: 54 },
    printDurationHours: 5.8,
    priceEur: 28.90,
    clientType: 'Consumer',
    city: 'The Hague',
    description: 'Dual-tone matte PLA ergonomic palm rest customized from a 3D hand scan, including brass heat-set insert pockets.',
  },
  {
    id: 'port-5',
    title: 'Drone Crash Guard & Vibration Absorber Kit',
    category: 'Robotics',
    image: 'drone',
    material: 'TPU',
    dimensions: { x: 160, y: 160, z: 25 },
    printDurationHours: 3.9,
    priceEur: 26.20,
    clientType: 'Student',
    city: 'Eindhoven',
    description: 'Flexible 95A TPU bumper guards designed to absorb high-velocity impacts during indoor autonomous drone swarm competitions.',
  },
  {
    id: 'port-6',
    title: 'Rare Classic Car Dashboard Climate Bezel',
    category: 'Automotive Restorations',
    image: 'bezel',
    material: 'PETG',
    dimensions: { x: 180, y: 65, z: 35 },
    printDurationHours: 4.1,
    priceEur: 32.00,
    clientType: 'Consumer',
    city: 'Rotterdam',
    description: 'Discontinued 1994 automotive dashboard vent re-engineered from a broken physical piece using 3D CAD design service.',
  },
];

export const INITIAL_ORDERS: CustomerOrder[] = [
  {
    id: 'ORD-NL-8492',
    createdAt: '2026-09-08T14:20:00Z',
    type: 'DIRECT_PRINT',
    status: 'IN_PRODUCTION',
    customer: {
      fullName: 'Bram van der Meer',
      email: 'bram.vdmeer@tudelft.nl',
      phone: '+31 6 1234 5678',
      city: 'Other',
      address: 'Mekelweg 4, 2628 CD Delft',
      isStudent: true,
      studentInstitution: 'TU Delft Aerospace Engineering',
    },
    details: {
      fileUrl: '',
      fileName: 'wing_rib_structural_v3.stl',
      volumeCm3: 84.5,
      dimensions: { x: 140, y: 65, z: 32 },
      material: 'PETG',
      infillPercentage: 40,
      colorCount: 1,
      deliverySpeed: 'COURIER_RANDSTAD',
      estimatedWeightGrams: 59.1,
      estimatedPrintTimeMinutes: 240,
      baseSetupFeeEur: 3.50,
      materialCostEur: 5.91,
      machineCostEur: 9.60,
      colorMultiplier: 1.0,
      shippingCostEur: 14.50,
      studentDiscountEur: 2.85,
      calculatedPriceEur: 30.66,
      specialInstructions: 'Please ensure 4 wall perimeters for bolt clearance.',
    },
  },
  {
    id: 'ORD-NL-8493',
    createdAt: '2026-09-09T09:15:00Z',
    type: 'DESIGN_AND_PRINT',
    status: 'QUOTE_SUBMITTED',
    customer: {
      fullName: 'Sophie de Jong',
      email: 's.dejong@archistudio-amsterdam.nl',
      phone: '+31 20 765 4321',
      city: 'Amsterdam',
      address: 'Prinsengracht 312, 1016 HX Amsterdam',
      isStudent: false,
    },
    details: {
      referenceImages: ['sketch_facade_elevation.jpg', 'facade_detail_photos.zip'],
      description: 'We need a scale model of an 18th-century canal house facade with open rear staircase. We have rough hand sketches and PDF elevation drawings, needing clean parametric CAD model ready for resin SLA printing.',
      targetDimensions: { x: 120, y: 220, z: 60 },
      functionalRequirements: 'Must assemble cleanly into an existing scale street master model with 0.2mm tolerance.',
      intendedUse: 'decorative',
      estimatedComplexity: 'COMPLEX',
      status: 'PENDING_REVIEW',
      quotedPriceEur: 185.00,
      estimatedTurnaroundDays: 2,
    },
  },
  {
    id: 'ORD-NL-8494',
    createdAt: '2026-09-09T11:45:00Z',
    type: 'DIRECT_PRINT',
    status: 'DISPATCHED',
    customer: {
      fullName: 'Lars Westerveld',
      email: 'lars@utrecht-maker.nl',
      phone: '+31 30 987 6543',
      city: 'Utrecht',
      address: 'Oudegracht 88, 3511 AP Utrecht',
      isStudent: false,
    },
    details: {
      fileUrl: '',
      fileName: 'camera_gimbal_arm_adapter.stl',
      volumeCm3: 32.2,
      dimensions: { x: 72, y: 48, z: 22 },
      material: 'ABS',
      infillPercentage: 100,
      colorCount: 1,
      deliverySpeed: 'EXPRESS',
      estimatedWeightGrams: 33.5,
      estimatedPrintTimeMinutes: 125,
      baseSetupFeeEur: 3.50,
      materialCostEur: 3.69,
      machineCostEur: 5.00,
      colorMultiplier: 1.0,
      shippingCostEur: 8.50,
      studentDiscountEur: 0,
      calculatedPriceEur: 20.69,
    },
  },
  {
    id: 'ORD-NL-8495',
    createdAt: '2026-09-09T16:30:00Z',
    type: 'DESIGN_AND_PRINT',
    status: 'QUOTE_SUBMITTED',
    customer: {
      fullName: 'Anouk Bakker',
      email: 'a.bakker@uu.nl',
      phone: '+31 6 4433 2211',
      city: 'Utrecht',
      address: 'Heidelberglaan 8, 3584 CS Utrecht',
      isStudent: true,
      studentInstitution: 'Utrecht University (Life Sciences)',
    },
    details: {
      referenceImages: ['pipette_holder_dimensions.png'],
      description: 'Custom ergonomic 6-position laboratory pipette carousel mount for sterile bench hoods with cable management clips.',
      targetDimensions: { x: 150, y: 150, z: 90 },
      functionalRequirements: 'Must be stable and resistant to alcohol / ethanol wipes (PETG or ABS).',
      intendedUse: 'functional',
      estimatedComplexity: 'MEDIUM',
      status: 'PENDING_REVIEW',
      quotedPriceEur: 85.00,
      estimatedTurnaroundDays: 1,
    },
  },
  {
    id: 'ORD-NL-8491',
    createdAt: '2026-09-07T10:00:00Z',
    type: 'DIRECT_PRINT',
    status: 'COMPLETED',
    customer: {
      fullName: 'Maarten de Vries',
      email: 'm.devries@denhaag-iot.nl',
      phone: '+31 70 332 1100',
      city: 'The Hague',
      address: 'Spui 12, 2511 BL Den Haag',
      isStudent: false,
    },
    details: {
      fileUrl: '',
      fileName: 'weather_sensor_enclosure_ip65.stl',
      volumeCm3: 110.0,
      dimensions: { x: 130, y: 85, z: 40 },
      material: 'PETG',
      infillPercentage: 40,
      colorCount: 2,
      deliverySpeed: 'STANDARD',
      estimatedWeightGrams: 81.0,
      estimatedPrintTimeMinutes: 310,
      baseSetupFeeEur: 3.50,
      materialCostEur: 8.10,
      machineCostEur: 12.40,
      colorMultiplier: 1.25,
      shippingCostEur: 4.95,
      studentDiscountEur: 0,
      calculatedPriceEur: 34.95,
    },
  },
];

export const CAD_COMPLEXITY_TIERS = [
  {
    id: 'SIMPLE' as const,
    title: 'Tier 1: Simple Geometric Design',
    turnaround: '1 Business Day',
    priceRange: '€35 – €65',
    typicalHours: '1–2 Engineering Hours',
    description: 'Direct geometric shapes, mounting plates, custom adapters, simple brackets, basic enclosures without moving parts.',
    examples: ['Flat camera mount', 'Spool holder arm', 'Wall bracket with screw holes', 'Simple box with lid'],
    features: ['1 revision included', 'STEP & STL export', 'Basic tolerance checks'],
  },
  {
    id: 'MEDIUM' as const,
    title: 'Tier 2: Functional / Mechanical Part',
    turnaround: '1–2 Business Days',
    priceRange: '€70 – €150',
    typicalHours: '3–5 Engineering Hours',
    popular: true,
    description: 'Assemblies, snap-fit enclosures, ergonomic handgrips, replacement gears, organic shapes, or models reverse-engineered from photos/calipers.',
    examples: ['Snap-fit electronics enclosure', 'Custom drone frame member', 'Gears & bearings mount', 'Ergonomic handle'],
    features: ['2 revisions included', 'Full mechanical clearance simulation', 'Production-ready files & print orientation guide'],
  },
  {
    id: 'COMPLEX' as const,
    title: 'Tier 3: Complex Multi-Part System',
    turnaround: '2–3 Business Days',
    priceRange: '€160 – €350+',
    typicalHours: '6+ Engineering Hours',
    description: 'High-tolerance mechanisms, multi-component assemblies with hinges or linkages, architectural scale models with interior detail, or specialized industrial engineering.',
    examples: ['Robotic gripper assembly', 'Architectural heritage building replica', 'Complex fluid manifold', 'Complete product prototype'],
    features: ['Dedicated engineering review', 'Detailed 3D tolerance stackup', 'Material optimization & structural FEA guidance'],
  },
];
