import { BenchmarkPortfolioItem, CustomerOrder, CustomerReview, DesignBenchmarkCard } from '@/types';

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    name: 'Sander de Wit',
    location: 'Haarlem (Spaarne)',
    role: 'Lead Industrial Designer, Studio Nord',
    rating: 5,
    date: '2 days ago',
    headline: 'Dispatched in 24 hours — snap-fit tolerances were spot on',
    comment:
      'We had a client presentation in Amsterdam and needed functional prototypes overnight. Uploaded the STEP file in the morning, verified dimensions in the browser, and had the parts delivered to our Haarlem studio the following afternoon. Crisp layer lines and zero warping.',
    avatarInitials: 'SW',
    verifiedOrder: 'Tough Enclosure Prototype',
  },
  {
    id: 'rev-2',
    name: 'Fleur van Dijk',
    location: 'Amsterdam (NDSM)',
    role: 'Hardware Product Manager, UrbanAero',
    rating: 5,
    date: '1 week ago',
    headline: 'Instant transparent pricing without the email delay',
    comment:
      'Most print hubs take 24–48 hours just to reply with a quote. PrintLab NL gave us an instant price, let us test 150% scaling on the spot, and dispatched via courier right on schedule. The multi-color AMS detailing was remarkable.',
    avatarInitials: 'FD',
    verifiedOrder: 'TU Delft Drone Propeller Guard',
  },
  {
    id: 'rev-3',
    name: 'Thijs Meijer',
    location: 'Utrecht (Science Park)',
    role: 'Robotics Research Engineer, UU Lab',
    rating: 5,
    date: '2 weeks ago',
    headline: 'Smooth communication and top-tier mechanical strength',
    comment:
      'Printed high-stress load brackets in Tough polymer. Communication was crystal clear, and the 1-working-day dispatch guarantee is genuinely dependable. Will be our primary manufacturing partner for university lab fixtures.',
    avatarInitials: 'TM',
    verifiedOrder: 'T-Joint Structural Bracket 60mm',
  },
  {
    id: 'rev-4',
    name: 'Anneke Jansen',
    location: 'Amsterdam-Zuid',
    role: 'Restoration Specialist',
    rating: 5,
    date: '3 weeks ago',
    headline: 'Designed from rough hand sketches and photos',
    comment:
      'I needed a discontinued gear for a 1970s turntable. I only had caliper photos and rough sketches. The engineer replied with a fixed quote within 1 business day, and the resulting part fit like a glove.',
    avatarInitials: 'AJ',
    verifiedOrder: 'Custom CAD Reverse Engineering',
  },
];

export const BENCHMARK_PORTFOLIO: BenchmarkPortfolioItem[] = [
  {
    id: 'port-1',
    title: 'Precision T-Joint Structural Bracket (60mm)',
    category: 'Functional Parts',
    image: 'bracket',
    material: 'TOUGH',
    dimensions: { x: 60, y: 53, z: 28 },
    printDurationHours: 2.5,
    priceEur: 18.50,
    clientType: 'Engineering Lab',
    city: 'Haarlem',
    description: 'High-strength structural bracket engineered for machine frame mounting with pre-modeled M4 counterbores.',
  },
  {
    id: 'port-2',
    title: 'Amsterdam Grachtenpand Facade Scale Model',
    category: 'Prototypes & Architecture',
    image: 'facade',
    material: 'STANDARD',
    dimensions: { x: 42, y: 99, z: 30 },
    printDurationHours: 4.8,
    priceEur: 28.40,
    clientType: 'Architecture Firm',
    city: 'Amsterdam',
    description: 'Crisp architectural miniature capturing delicate step-gable brickwork and period window mullions in matte white.',
  },
  {
    id: 'port-3',
    title: 'Multi-Color Drone Propeller Guard & Arm',
    category: 'Aesthetic / Multi-Color',
    image: 'drone',
    material: 'STANDARD',
    dimensions: { x: 83, y: 83, z: 10 },
    printDurationHours: 1.8,
    priceEur: 16.90,
    clientType: 'Consumer',
    city: 'Utrecht',
    description: 'Bambu Lab AMS dual-color high-visibility safety bumper for indoor autonomous navigation testing.',
  },
  {
    id: 'port-4',
    title: 'Ultra-Smooth Medical Luer Adapter',
    category: 'Prototypes & Medical',
    image: 'valve',
    material: 'RESIN',
    dimensions: { x: 32, y: 24, z: 40 },
    printDurationHours: 2.0,
    priceEur: 22.00,
    clientType: 'Engineering Lab',
    city: 'Haarlem',
    description: 'High-resolution SLA resin manifold with zero porosity, airtight threads, and glass-like smoothness.',
  },
  {
    id: 'port-5',
    title: 'Ergonomic Dial & Tactile Volume Knob',
    category: 'Functional Parts',
    image: 'dial',
    material: 'TOUGH',
    dimensions: { x: 36, y: 36, z: 20 },
    printDurationHours: 1.2,
    priceEur: 14.80,
    clientType: 'Consumer',
    city: 'Amsterdam',
    description: 'Custom knurled grip with tight D-shaft tolerance for audio mixing console restoration.',
  },
  {
    id: 'port-6',
    title: 'Snap-Fit Weatherproof IoT Enclosure',
    category: 'Prototypes',
    image: 'box',
    material: 'TOUGH',
    dimensions: { x: 110, y: 70, z: 35 },
    printDurationHours: 3.5,
    priceEur: 26.50,
    clientType: 'Consumer',
    city: 'Utrecht',
    description: 'Dual-part enclosure with integrated rubber O-ring seal groove and cable gland knockouts.',
  },
];

export const DESIGN_BENCHMARK_CARDS: DesignBenchmarkCard[] = [
  {
    id: 'bench-1',
    tierNumber: 1,
    title: 'Small Clip / Hook / Basic Piece',
    priceRange: '€15 – €25',
    turnaround: '1 Business Day',
    description: 'Simple geometric item or mounting clip modeled from basic dimensions or a photograph next to a coin.',
    idealFor: 'Broken plastic clips, cable holders, hooks, wall tabs',
    exampleParts: ['Dishwasher basket wheel', 'Blind cord guide', 'Headphone desk hook', 'Battery door latch'],
    iconType: 'clip',
  },
  {
    id: 'bench-2',
    tierNumber: 2,
    title: 'Medium Desk Accessory / Enclosure',
    priceRange: '€35 – €60',
    turnaround: '1 Business Day',
    description: 'Custom enclosure, ergonomic stand, or accessory requiring simple internal pockets or snap-fit lid.',
    idealFor: 'Custom Raspberry Pi case, phone desk dock, remote control holder',
    exampleParts: ['Snap-fit sensor case', 'Angled keyboard riser', 'Gridfinity organizer tray', 'Smart home wall mount'],
    iconType: 'enclosure',
  },
  {
    id: 'bench-3',
    tierNumber: 3,
    title: 'Heavy-Duty Mechanical Bracket / Part',
    priceRange: '€75 – €130',
    turnaround: '1–2 Business Days',
    description: 'Load-bearing replacement component requiring precise caliper tolerances, counterbores, or gear teeth.',
    idealFor: 'Automotive interior clips, robotic brackets, machinery gears, motor mounts',
    exampleParts: ['Sunroof mechanism slider', 'Coffee grinder drive gear', 'Bicycle pannier rail clip', 'Drill press stop'],
    iconType: 'bracket',
  },
  {
    id: 'bench-4',
    tierNumber: 4,
    title: 'Full Custom 3D Design From Scratch',
    priceRange: '€150+',
    turnaround: '2–3 Business Days',
    description: 'Complete multi-component design engineered from rough ideas, patent concepts, or hand sketches.',
    idealFor: 'New product prototypes, complex moving assemblies, architectural scale replicas',
    exampleParts: ['Full consumer product prototype', 'Multi-part mechanical linkage', 'Custom drone frame assembly'],
    iconType: 'custom',
  },
];

export const INITIAL_ORDERS: CustomerOrder[] = [
  {
    id: 'ORD-NL-7210',
    createdAt: '2026-09-10T11:20:00Z',
    type: 'DIRECT_PRINT',
    status: 'IN_PRODUCTION',
    customer: {
      fullName: 'Sander de Wit',
      email: 'sander@studionord.nl',
      phone: '+31 6 2345 6789',
      city: 'Haarlem',
      address: 'Gierstraat 34, 2011 GD Haarlem',
    },
    details: {
      fileUrl: '',
      fileName: 't_joint_mount_bracket_60mm.stl',
      baseDimensions: { x: 60, y: 53, z: 28 },
      dimensions: { x: 60, y: 53, z: 28 },
      scaleFactor: 1.0,
      baseVolumeCm3: 47.0,
      volumeCm3: 47.0,
      material: 'TOUGH',
      colorOption: 'SINGLE',
      colorCount: 1,
      deliverySpeed: 'COURIER_RANDSTAD',
      estimatedWeightGrams: 22.7,
      estimatedPrintTimeMinutes: 110,
      estimatedDeliveryDate: 'Tomorrow by 18:00',
      baseSetupFeeEur: 3.50,
      materialCostEur: 2.27,
      machineCostEur: 4.40,
      colorMultiplier: 1.0,
      shippingCostEur: 12.50,
      calculatedPriceEur: 22.67,
    },
  },
  {
    id: 'ORD-NL-7211',
    createdAt: '2026-09-11T09:40:00Z',
    type: 'DESIGN_AND_PRINT',
    status: 'QUOTE_SUBMITTED',
    customer: {
      fullName: 'Fleur van Dijk',
      email: 'fleur@urbanaero.io',
      phone: '+31 20 889 1234',
      city: 'Amsterdam',
      address: 'NDSM-Plein 28, 1033 WC Amsterdam',
    },
    details: {
      referenceImages: ['propeller_bumper_measurements.jpg'],
      description: 'Need a dual-ring bumper protector for an autonomous indoor inspection drone. Outer diameter 85mm with 3-hole M2 motor mount pattern.',
      targetDimensions: { x: 85, y: 85, z: 12 },
      customerNotes: 'Must be lightweight but capable of absorbing 15 km/h wall impact without cracking.',
      estimatedComplexity: 'MEDIUM',
      benchmarkCardId: 'bench-2',
      status: 'PENDING_REVIEW',
      quotedPriceEur: 48.00,
      estimatedTurnaroundDays: 1,
    },
  },
];
